name: Publish (rust bin)

permissions:
  id-token: write
  contents: write
  attestations: write

on:
  push:

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build
      run: |
        cd rust
        cargo build --release    
    - uses: actions/attest-build-provenance@main
      with:
        subject-path: rust/target/release/flatpatch
    - name: Upload attestation
      uses: actions/upload-artifact@main
      with:
        name: build-provenance
        path: |
          provenance.intoto.json
          provenance.jws
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.ACCESS_TOKEN }}
        repo_name: pheiduck/flatpatch
        file: rust/target/release/flatpatch
        asset_name: flatpatch
        tag: ${{ github.ref }}
        overwrite: true
        body: "binaries for production use"
