name: Publish (rust bin)

on:
  push:

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build
      run: |
        cd rust
        cargo build --release    
    - uses: actions/attest-build-provenance@main
      with:
        subject-path: flatpatch
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_name: pheiduck/flatpatch
        repo_token: ${{ secrets.ACCESS_TOKEN }}
        file: rust/target/release/flatpatch
        asset_name: flatpatch
        tag: ${{ github.ref }}
        overwrite: true
        body: "binaries for production use"
